export const a = {
  type: "view",
  name: "Home",
  style: {
    width: 1440,
    height: 900,
    backgroundColor: "#050816",
  },
  scrollDirection: "vertical",
  scrollBarVisibility: "hidden",
  children: [
    {
      type: "view",
      name: "bgInset",
      style: {
        position: "absolute",
        left: -504,
        top: -315,
        width: 2448,
        height: 1530,
        zIndex: 0,
      },
      children: [
        {
          type: "view",
          name: "bgRadial1",
          style: {
            position: "absolute",
            left: 0,
            top: 0,
            width: 2448,
            height: 1530,
            linearGradient: {
              type: "radial",
              center: { x: 0.2, y: 0.15 },
              radius: 0.95,
              colors: [
                { offset: 0, color: "rgba(168,85,247,0.32)" },
                { offset: 0.55, color: "rgba(168,85,247,0)" },
                { offset: 1, color: "rgba(168,85,247,0)" },
              ],
            },
          },
        },
        {
          type: "view",
          name: "bgRadial2",
          style: {
            position: "absolute",
            left: 0,
            top: 0,
            width: 2448,
            height: 1530,
            linearGradient: {
              type: "radial",
              center: { x: 0.72, y: 0.3 },
              radius: 0.95,
              colors: [
                { offset: 0, color: "rgba(59,130,246,0.26)" },
                { offset: 0.58, color: "rgba(59,130,246,0)" },
                { offset: 1, color: "rgba(59,130,246,0)" },
              ],
            },
          },
        },
        {
          type: "view",
          name: "bgRadial3",
          style: {
            position: "absolute",
            left: 0,
            top: 0,
            width: 2448,
            height: 1530,
            linearGradient: {
              type: "radial",
              center: { x: 0.6, y: 0.8 },
              radius: 0.95,
              colors: [
                { offset: 0, color: "rgba(34,197,94,0.18)" },
                { offset: 0.62, color: "rgba(34,197,94,0)" },
                { offset: 1, color: "rgba(34,197,94,0)" },
              ],
            },
          },
        },
      ],
    },
    {
      type: "view",
      name: "bgOverlay",
      style: {
        position: "absolute",
        left: 0,
        top: 0,
        width: 1440,
        height: 900,
        zIndex: 1,
        linearGradient: {
          angle: 180,
          start: { x: 0, y: 0 },
          end: { x: 0, y: 1 },
          colors: [
            { offset: 0, color: "rgba(255,255,255,0.05)" },
            { offset: 0.3, color: "rgba(255,255,255,0)" },
            { offset: 1, color: "rgba(255,255,255,0.03)" },
          ],
        },
      },
    },
    {
      type: "view",
      name: "container",
      style: {
        width: 1152,
        alignSelf: "center",
        paddingTop: 40,
        paddingRight: 24,
        paddingBottom: 40,
        paddingLeft: 24,
        flexDirection: "column",
        alignItems: "stretch",
        zIndex: 2,
      },
      children: [
        {
          type: "view",
          name: "topbar",
          style: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
          },
          children: [
            {
              type: "view",
              name: "brand",
              style: { flexDirection: "row", alignItems: "center", gap: 8 },
              children: [
                {
                  type: "view",
                  name: "brandIcon",
                  style: {
                    width: 36,
                    height: 36,
                    borderRadius: 16,
                    backgroundColor: "rgba(255,255,255,0.10)",
                    borderColor: "rgba(255,255,255,0.15)",
                    borderWidth: 1,
                    justifyContent: "center",
                    alignItems: "center",
                  },
                  children: [
                    {
                      type: "text",
                      name: "brandIconText",
                      style: {
                        fontSize: 18,
                        fontWeight: 800,
                        color: "rgba(255,255,255,0.90)",
                        lineHeight: 18,
                        textAlign: "center",
                      },
                      content: "✦",
                    },
                  ],
                },
                {
                  type: "view",
                  name: "brandText",
                  style: { flexDirection: "column" },
                  children: [
                    {
                      type: "text",
                      name: "tagline",
                      style: {
                        fontSize: 14,
                        fontWeight: 700,
                        color: "rgba(255,255,255,0.92)",
                        lineHeight: 16,
                      },
                      content: "Yoga Canvas",
                    },
                    {
                      type: "text",
                      name: "subtitle",
                      style: {
                        marginTop: 2,
                        fontSize: 11,
                        fontWeight: 600,
                        color: "rgba(255,255,255,0.55)",
                        lineHeight: 14,
                      },
                      content: "基于 Yoga Layout 的 Canvas 画布引擎",
                    },
                  ],
                },
              ],
            },
            {
              type: "view",
              name: "toggleLocale",
              style: {
                paddingLeft: 12,
                paddingRight: 12,
                paddingTop: 10,
                paddingBottom: 10,
                borderRadius: 24,
                backgroundColor: "rgba(255,255,255,0.07)",
                borderColor: "rgba(255,255,255,0.12)",
                borderWidth: 1,
              },
              children: [
                {
                  type: "text",
                  name: "toggleLocaleText",
                  style: {
                    fontSize: 11,
                    fontWeight: 700,
                    color: "rgba(255,255,255,0.75)",
                    lineHeight: 14,
                    textAlign: "center",
                    whiteSpace: "nowrap",
                  },
                  content: "中文",
                },
              ],
            },
          ],
        },
        {
          type: "view",
          name: "hero",
          style: { marginTop: 56 },
          children: [
            {
              type: "view",
              name: "heroTitle",
              style: { marginTop: 24 },
              children: [
                {
                  type: "text",
                  name: "heroLead",
                  style: {
                    fontSize: 46,
                    fontWeight: 800,
                    color: "rgba(255,255,255,0.95)",
                    lineHeight: 48,
                  },
                  content: "一个面向",
                },
                {
                  type: "text",
                  name: "heroHighlight",
                  style: {
                    marginTop: 6,
                    fontSize: 46,
                    fontWeight: 800,
                    color: "rgba(216,180,254,0.92)",
                    lineHeight: 48,
                  },
                  content: "布局与可视化编辑",
                },
                {
                  type: "text",
                  name: "heroTail",
                  style: {
                    marginTop: 6,
                    fontSize: 46,
                    fontWeight: 800,
                    color: "rgba(255,255,255,0.95)",
                    lineHeight: 48,
                  },
                  content: "的 Canvas 引擎与组件库",
                },
              ],
            },
            {
              type: "text",
              name: "intro",
              style: {
                marginTop: 16,
                width: 560,
                fontSize: 14,
                fontWeight: 500,
                color: "rgba(255,255,255,0.65)",
                lineHeight: 24,
              },
              content:
                "用 Yoga（Flexbox）计算布局，把 View/Text/Image/ScrollView 这类节点树渲染到 Canvas；并提供命中测试、选中高亮、缩放平移与属性调参等编辑能力，支持导出 JSON / DOM / 图片，适配 H5 与微信小程序。",
            },
            {
              type: "view",
              name: "actions",
              style: { marginTop: 32 },
              children: [
                {
                  type: "view",
                  name: "cta",
                  style: {
                    flexDirection: "row",
                    alignItems: "center",
                    gap: 8,
                    paddingLeft: 16,
                    paddingRight: 16,
                    paddingTop: 12,
                    paddingBottom: 12,
                    borderRadius: 16,
                    backgroundColor: "#ffffff",
                    boxShadow: {
                      offsetX: 0,
                      offsetY: 18,
                      blur: 60,
                      color: "rgba(0,0,0,0.35)",
                    },
                  },
                  children: [
                    {
                      type: "text",
                      name: "ctaLabel",
                      style: {
                        fontSize: 14,
                        fontWeight: 800,
                        color: "#0f172a",
                        lineHeight: 16,
                        whiteSpace: "nowrap",
                      },
                      content: "立即体验",
                    },
                    {
                      type: "text",
                      name: "ctaArrow",
                      style: {
                        fontSize: 16,
                        fontWeight: 900,
                        color: "#0f172a",
                        lineHeight: 16,
                        whiteSpace: "nowrap",
                      },
                      content: "→",
                    },
                  ],
                },
              ],
            },
            {
              type: "view",
              name: "stats",
              style: {
                marginTop: 40,
                width: 560,
                flexDirection: "row",
                flexWrap: "wrap",
                gap: 12,
              },
              children: [
                {
                  type: "view",
                  name: "stat_layout",
                  style: {
                    width: 274,
                    backgroundColor: "rgba(255,255,255,0.07)",
                    borderColor: "rgba(255,255,255,0.12)",
                    borderWidth: 1,
                    borderRadius: 16,
                    paddingLeft: 16,
                    paddingRight: 16,
                    paddingTop: 12,
                    paddingBottom: 12,
                    boxShadow: {
                      offsetX: 0,
                      offsetY: 18,
                      blur: 60,
                      color: "rgba(0,0,0,0.18)",
                    },
                  },
                  children: [
                    {
                      type: "text",
                      name: "stat_layout_label",
                      style: {
                        fontSize: 11,
                        fontWeight: 700,
                        color: "rgba(255,255,255,0.55)",
                        lineHeight: 14,
                      },
                      content: "Yoga 布局",
                    },
                    {
                      type: "text",
                      name: "stat_layout_value",
                      style: {
                        marginTop: 4,
                        fontSize: 14,
                        fontWeight: 800,
                        color: "rgba(255,255,255,0.90)",
                        lineHeight: 18,
                      },
                      content: "Yoga Flexbox",
                    },
                  ],
                },
                {
                  type: "view",
                  name: "stat_render",
                  style: {
                    width: 274,
                    backgroundColor: "rgba(255,255,255,0.07)",
                    borderColor: "rgba(255,255,255,0.12)",
                    borderWidth: 1,
                    borderRadius: 16,
                    paddingLeft: 16,
                    paddingRight: 16,
                    paddingTop: 12,
                    paddingBottom: 12,
                    boxShadow: {
                      offsetX: 0,
                      offsetY: 18,
                      blur: 60,
                      color: "rgba(0,0,0,0.18)",
                    },
                  },
                  children: [
                    {
                      type: "text",
                      name: "stat_render_label",
                      style: {
                        fontSize: 11,
                        fontWeight: 700,
                        color: "rgba(255,255,255,0.55)",
                        lineHeight: 14,
                      },
                      content: "渲染输出",
                    },
                    {
                      type: "text",
                      name: "stat_render_value",
                      style: {
                        marginTop: 4,
                        fontSize: 14,
                        fontWeight: 800,
                        color: "rgba(255,255,255,0.90)",
                        lineHeight: 18,
                      },
                      content: "Canvas (H5/WX) / DOM",
                    },
                  ],
                },
                {
                  type: "view",
                  name: "stat_editor",
                  style: {
                    width: 274,
                    backgroundColor: "rgba(255,255,255,0.07)",
                    borderColor: "rgba(255,255,255,0.12)",
                    borderWidth: 1,
                    borderRadius: 16,
                    paddingLeft: 16,
                    paddingRight: 16,
                    paddingTop: 12,
                    paddingBottom: 12,
                    boxShadow: {
                      offsetX: 0,
                      offsetY: 18,
                      blur: 60,
                      color: "rgba(0,0,0,0.18)",
                    },
                  },
                  children: [
                    {
                      type: "text",
                      name: "stat_editor_label",
                      style: {
                        fontSize: 11,
                        fontWeight: 700,
                        color: "rgba(255,255,255,0.55)",
                        lineHeight: 14,
                      },
                      content: "编辑交互",
                    },
                    {
                      type: "text",
                      name: "stat_editor_value",
                      style: {
                        marginTop: 4,
                        fontSize: 14,
                        fontWeight: 800,
                        color: "rgba(255,255,255,0.90)",
                        lineHeight: 18,
                      },
                      content: "HitTest / Select / Inspect",
                    },
                  ],
                },
                {
                  type: "view",
                  name: "stat_export",
                  style: {
                    width: 274,
                    backgroundColor: "rgba(255,255,255,0.07)",
                    borderColor: "rgba(255,255,255,0.12)",
                    borderWidth: 1,
                    borderRadius: 16,
                    paddingLeft: 16,
                    paddingRight: 16,
                    paddingTop: 12,
                    paddingBottom: 12,
                    boxShadow: {
                      offsetX: 0,
                      offsetY: 18,
                      blur: 60,
                      color: "rgba(0,0,0,0.18)",
                    },
                  },
                  children: [
                    {
                      type: "text",
                      name: "stat_export_label",
                      style: {
                        fontSize: 11,
                        fontWeight: 700,
                        color: "rgba(255,255,255,0.55)",
                        lineHeight: 14,
                      },
                      content: "导出格式",
                    },
                    {
                      type: "text",
                      name: "stat_export_value",
                      style: {
                        marginTop: 4,
                        fontSize: 14,
                        fontWeight: 800,
                        color: "rgba(255,255,255,0.90)",
                        lineHeight: 18,
                      },
                      content: "JSON / DOM / Image",
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
