import type { NodeDescriptor } from "@yoga-canvas/core";
import { getLegacyDemoDescriptor } from "../hooks/useNodeTree";

export type SeedTemplate = {
  id: string;
  name: string;
  description?: string;
  descriptor: NodeDescriptor;
};

const SHARE_POSTER_HERO_SRC = `data:image/svg+xml;utf8,${encodeURIComponent(
  `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800">
      <defs>
        <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stop-color="#0b1220"/>
          <stop offset="1" stop-color="#111827"/>
        </linearGradient>
        <radialGradient id="g1" cx="30%" cy="20%" r="60%">
          <stop offset="0" stop-color="rgba(99,102,241,0.65)"/>
          <stop offset="1" stop-color="rgba(99,102,241,0)"/>
        </radialGradient>
        <radialGradient id="g2" cx="72%" cy="62%" r="65%">
          <stop offset="0" stop-color="rgba(236,72,153,0.55)"/>
          <stop offset="1" stop-color="rgba(236,72,153,0)"/>
        </radialGradient>
        <filter id="blur" x="-20%" y="-20%" width="140%" height="140%">
          <feGaussianBlur stdDeviation="18"/>
        </filter>
      </defs>
      <rect width="1200" height="800" fill="url(#bg)"/>
      <rect width="1200" height="800" fill="url(#g1)"/>
      <rect width="1200" height="800" fill="url(#g2)"/>
      <g filter="url(#blur)" opacity="0.9">
        <circle cx="220" cy="160" r="160" fill="rgba(34,211,238,0.35)"/>
        <circle cx="1030" cy="610" r="220" fill="rgba(129,140,248,0.32)"/>
        <circle cx="860" cy="180" r="140" fill="rgba(16,185,129,0.22)"/>
      </g>
      <g opacity="0.12">
        <path d="M0 560 C 220 480 360 650 560 560 C 760 470 880 560 1200 460 L 1200 800 L 0 800 Z" fill="#ffffff"/>
      </g>
    </svg>`,
)}`;

const SHARE_POSTER_QR_SRC =
  "https://api.qrserver.com/v1/create-qr-code/?size=280x280&data=https%3A%2F%2Fexample.com";

export const seedTemplates: SeedTemplate[] = [
  {
    id: "seed_blank",
    name: "空白模板",
    description: "从零开始搭建布局",
    descriptor: {
      type: "view",
      name: "Root",
      style: {
        width: 375,
        height: 667,
        flexDirection: "column",
        backgroundColor: "#ffffff",
      },
      children: [],
    },
  },
  {
    id: "seed_legacy_demo",
    name: "展示 Layout",
    description: "包含常用节点与样式示例",
    descriptor: getLegacyDemoDescriptor(),
  },
  {
    id: "seed_share_poster",
    name: "分享海报模板",
    description: "带海报卡片与二维码示例",
    descriptor: {
      type: "view",
      name: "Root",
      style: {
        width: 375,
        height: "auto",
        flexDirection: "column",
        backgroundColor: "#0b1220",
        padding: 16,
        gap: 12,
      },
      children: [
        {
          type: "view",
          name: "PosterCard",
          style: {
            flexDirection: "column",
            backgroundColor: "#0f172a",
            linearGradient: {
              start: { x: 0, y: 0 },
              end: { x: 1, y: 1 },
              colors: [
                { offset: 0, color: "#0f172a" },
                { offset: 1, color: "#111827" },
              ],
            },
            borderRadius: 20,
            padding: 16,
            gap: 12,
            boxShadow: {
              color: "rgba(2,6,23,0.55)",
              blur: 20,
              offsetX: 0,
              offsetY: 10,
            },
          },
          children: [
            {
              type: "view",
              name: "BrandRow",
              style: { flexDirection: "row", alignItems: "center", gap: 10 },
              children: [
                {
                  type: "view",
                  name: "BrandMark",
                  style: {
                    width: 28,
                    height: 28,
                    borderRadius: 10,
                    backgroundColor: "rgba(99,102,241,0.24)",
                    borderWidth: 1,
                    borderColor: "rgba(129,140,248,0.28)",
                  },
                },
                {
                  type: "view",
                  name: "BrandText",
                  style: { flexDirection: "column", gap: 1, flex: 1 },
                  children: [
                    {
                      type: "text",
                      name: "BrandName",
                      content: "Yoga Canvas",
                      style: {
                        fontSize: 13,
                        fontWeight: 700,
                        color: "#e2e8f0",
                        lineHeight: 1.2,
                        whiteSpace: "nowrap",
                      },
                    },
                    {
                      type: "text",
                      name: "BrandSub",
                      content: "分享海报 · 小程序风格",
                      style: {
                        fontSize: 10,
                        color: "rgba(226,232,240,0.68)",
                        lineHeight: 1.2,
                        whiteSpace: "nowrap",
                      },
                    },
                  ],
                },
                {
                  type: "view",
                  name: "Badge",
                  style: {
                    paddingLeft: 10,
                    paddingRight: 10,
                    paddingTop: 6,
                    paddingBottom: 6,
                    borderRadius: 999,
                    backgroundColor: "rgba(16,185,129,0.16)",
                    borderWidth: 1,
                    borderColor: "rgba(52,211,153,0.22)",
                  },
                  children: [
                    {
                      type: "text",
                      content: "HOT",
                      style: {
                        fontSize: 10,
                        fontWeight: 800,
                        color: "#6ee7b7",
                        whiteSpace: "nowrap",
                      },
                    },
                  ],
                },
              ],
            },
            {
              type: "view",
              name: "HeroImage",
              style: {
                height: 240,
                borderRadius: 18,
                overflow: "hidden",
                backgroundColor: "rgba(255,255,255,0.06)",
                borderWidth: 1,
                borderColor: "rgba(148,163,184,0.18)",
                linearGradient: {
                  start: { x: 0, y: 0 },
                  end: { x: 1, y: 1 },
                  colors: [
                    { offset: 0, color: "rgba(99,102,241,0.24)" },
                    { offset: 1, color: "rgba(236,72,153,0.18)" },
                  ],
                },
              },
              children: [
                {
                  type: "image",
                  name: "HeroPhoto",
                  src: SHARE_POSTER_HERO_SRC,
                  objectFit: "cover",
                  style: {
                    position: "absolute",
                    left: 0,
                    top: 0,
                    width: "100%",
                    height: "100%",
                  },
                },
                {
                  type: "view",
                  name: "HeroGlow1",
                  style: {
                    position: "absolute",
                    left: -60,
                    top: -60,
                    width: 200,
                    height: 200,
                    borderRadius: 999,
                    backgroundColor: "rgba(34,211,238,0.22)",
                  },
                },
                {
                  type: "view",
                  name: "HeroGlow2",
                  style: {
                    position: "absolute",
                    right: -80,
                    bottom: -80,
                    width: 240,
                    height: 240,
                    borderRadius: 999,
                    backgroundColor: "rgba(129,140,248,0.22)",
                  },
                },
                {
                  type: "view",
                  name: "HeroCaption",
                  style: {
                    position: "absolute",
                    left: 14,
                    bottom: 14,
                    right: 14,
                    borderRadius: 14,
                    backgroundColor: "rgba(2,6,23,0.30)",
                    paddingLeft: 12,
                    paddingRight: 12,
                    paddingTop: 10,
                    paddingBottom: 10,
                    borderWidth: 1,
                    borderColor: "rgba(148,163,184,0.18)",
                  },
                  children: [
                    {
                      type: "text",
                      content: "今日推荐 · 把内容一键做成分享海报",
                      style: {
                        fontSize: 12,
                        fontWeight: 800,
                        color: "#e2e8f0",
                        whiteSpace: "nowrap",
                      },
                    },
                  ],
                },
              ],
            },
            {
              type: "view",
              name: "Copy",
              style: { flexDirection: "column", gap: 6 },
              children: [
                {
                  type: "text",
                  name: "Title",
                  content: "把你喜欢的内容做成海报",
                  style: {
                    fontSize: 18,
                    fontWeight: 800,
                    color: "#ffffff",
                    lineHeight: 1.2,
                    whiteSpace: "normal",
                  },
                },
                {
                  type: "text",
                  name: "Subtitle",
                  content: "一键生成分享图，长按识别二维码，立即体验。",
                  style: {
                    fontSize: 12,
                    color: "rgba(255,255,255,0.78)",
                    lineHeight: 1.6,
                    whiteSpace: "normal",
                  },
                },
              ],
            },
            {
              type: "view",
              name: "BottomBar",
              style: {
                flexDirection: "row",
                alignItems: "center",
                gap: 12,
                paddingTop: 10,
                borderWidth: 1,
                borderColor: "rgba(148,163,184,0.16)",
                borderRadius: 16,
                backgroundColor: "rgba(255,255,255,0.05)",
                paddingLeft: 12,
                paddingRight: 12,
                paddingBottom: 12,
              },
              children: [
                {
                  type: "view",
                  name: "QRCode",
                  style: {
                    width: 70,
                    height: 70,
                    borderRadius: 14,
                    backgroundColor: "#ffffff",
                    padding: 8,
                  },
                  children: [
                    {
                      type: "image",
                      name: "QRImage",
                      src: SHARE_POSTER_QR_SRC,
                      objectFit: "contain",
                      style: { width: "100%", height: "100%" },
                    },
                  ],
                },
                {
                  type: "view",
                  name: "Hint",
                  style: { flex: 1, flexDirection: "column", gap: 4 },
                  children: [
                    {
                      type: "text",
                      content: "长按识别二维码",
                      style: {
                        fontSize: 13,
                        fontWeight: 800,
                        color: "#e2e8f0",
                        whiteSpace: "nowrap",
                      },
                    },
                    {
                      type: "text",
                      content: "进入小程序 · 查看更多",
                      style: {
                        fontSize: 11,
                        color: "rgba(226,232,240,0.72)",
                        whiteSpace: "nowrap",
                      },
                    },
                    {
                      type: "view",
                      name: "TinyTags",
                      style: { flexDirection: "row", gap: 6, flexWrap: "wrap" },
                      children: [
                        {
                          type: "view",
                          name: "Tag1",
                          style: {
                            paddingLeft: 8,
                            paddingRight: 8,
                            paddingTop: 4,
                            paddingBottom: 4,
                            borderRadius: 999,
                            backgroundColor: "rgba(99,102,241,0.18)",
                          },
                          children: [
                            {
                              type: "text",
                              content: "高清导出",
                              style: {
                                fontSize: 10,
                                color: "#c7d2fe",
                                whiteSpace: "nowrap",
                              },
                            },
                          ],
                        },
                        {
                          type: "view",
                          name: "Tag2",
                          style: {
                            paddingLeft: 8,
                            paddingRight: 8,
                            paddingTop: 4,
                            paddingBottom: 4,
                            borderRadius: 999,
                            backgroundColor: "rgba(236,72,153,0.18)",
                          },
                          children: [
                            {
                              type: "text",
                              content: "布局引擎",
                              style: {
                                fontSize: 10,
                                color: "#fbcfe8",
                                whiteSpace: "nowrap",
                              },
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  },
  {
    id: "seed_home_page",
    name: "Home Page",
    description: "HomePage Layout",
    descriptor: {
      type: "view",
      name: "HomePage",
      style: {
        width: 1440,
        height: 900,
        backgroundColor: "#050816",
        linearGradient: null,
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 0,
        opacity: 1,
        rotate: 0,
        boxShadow: null,
        zIndex: 0,
      },
      children: [
        {
          type: "view",
          name: "bgInset",
          style: {
            width: 1440,
            height: 900,
            position: "absolute",
            top: 0,
            left: 0,
            backgroundColor: "transparent",
            linearGradient: null,
            borderColor: "transparent",
            borderWidth: 0,
            borderRadius: 0,
            opacity: 1,
            rotate: 0,
            boxShadow: null,
            zIndex: 0,
          },
          children: [
            {
              type: "view",
              name: "bgRadial1",
              style: {
                width: 1440,
                height: 900,
                position: "absolute",
                top: 0,
                left: 0,
                backgroundColor: "transparent",
                linearGradient: {
                  type: "radial",
                  center: {
                    x: 0.2,
                    y: 0.15,
                  },
                  radius: 0.95,
                  colors: [
                    {
                      offset: 0,
                      color: "rgba(168,85,247,0.32)",
                    },
                    {
                      offset: 0.55,
                      color: "rgba(168,85,247,0)",
                    },
                    {
                      offset: 1,
                      color: "rgba(168,85,247,0)",
                    },
                  ],
                },
                borderColor: "transparent",
                borderWidth: 0,
                borderRadius: 0,
                opacity: 1,
                rotate: 0,
                boxShadow: null,
                zIndex: 0,
              },
              children: [],
            },
            {
              type: "view",
              name: "bgRadial2",
              style: {
                width: 1440,
                height: 900,
                position: "absolute",
                top: 0,
                left: 0,
                backgroundColor: "transparent",
                linearGradient: {
                  type: "radial",
                  center: {
                    x: 0.72,
                    y: 0.3,
                  },
                  radius: 0.95,
                  colors: [
                    {
                      offset: 0,
                      color: "rgba(59,130,246,0.26)",
                    },
                    {
                      offset: 0.58,
                      color: "rgba(59,130,246,0)",
                    },
                    {
                      offset: 1,
                      color: "rgba(59,130,246,0)",
                    },
                  ],
                },
                borderColor: "transparent",
                borderWidth: 0,
                borderRadius: 0,
                opacity: 1,
                rotate: 0,
                boxShadow: null,
                zIndex: 0,
              },
              children: [],
            },
            {
              type: "view",
              name: "bgRadial3",
              style: {
                width: 1440,
                height: 900,
                position: "absolute",
                top: 0,
                left: 0,
                backgroundColor: "transparent",
                linearGradient: {
                  type: "radial",
                  center: {
                    x: 0.6,
                    y: 0.8,
                  },
                  radius: 0.95,
                  colors: [
                    {
                      offset: 0,
                      color: "rgba(34,197,94,0.18)",
                    },
                    {
                      offset: 0.62,
                      color: "rgba(34,197,94,0)",
                    },
                    {
                      offset: 1,
                      color: "rgba(34,197,94,0)",
                    },
                  ],
                },
                borderColor: "transparent",
                borderWidth: 0,
                borderRadius: 0,
                opacity: 1,
                rotate: 0,
                boxShadow: null,
                zIndex: 0,
              },
              children: [],
            },
          ],
        },
        {
          type: "view",
          name: "bgOverlay",
          style: {
            width: 1440,
            height: 900,
            position: "absolute",
            top: 0,
            left: 0,
            backgroundColor: "transparent",
            linearGradient: {
              angle: 180,
              start: {
                x: 0,
                y: 0,
              },
              end: {
                x: 0,
                y: 1,
              },
              colors: [
                {
                  offset: 0,
                  color: "rgba(255,255,255,0.05)",
                },
                {
                  offset: 0.3,
                  color: "rgba(255,255,255,0)",
                },
                {
                  offset: 1,
                  color: "rgba(255,255,255,0.03)",
                },
              ],
            },
            borderColor: "transparent",
            borderWidth: 0,
            borderRadius: 0,
            opacity: 1,
            rotate: 0,
            boxShadow: null,
            zIndex: 1,
          },
          children: [],
        },
        {
          type: "view",
          name: "container",
          style: {
            width: 1152,
            flexDirection: "column",
            alignItems: "stretch",
            alignSelf: "center",
            paddingTop: 40,
            paddingRight: 24,
            paddingBottom: 40,
            paddingLeft: 24,
            backgroundColor: "transparent",
            linearGradient: null,
            borderColor: "transparent",
            borderWidth: 0,
            borderRadius: 0,
            opacity: 1,
            rotate: 0,
            boxShadow: null,
            zIndex: 2,
          },
          children: [
            {
              type: "view",
              name: "topbar",
              style: {
                flexDirection: "row",
                justifyContent: "space-between",
                alignItems: "center",
                backgroundColor: "transparent",
                linearGradient: null,
                borderColor: "transparent",
                borderWidth: 0,
                borderRadius: 0,
                opacity: 1,
                rotate: 0,
                boxShadow: null,
                zIndex: 0,
              },
              children: [
                {
                  type: "view",
                  name: "brand",
                  style: {
                    flexDirection: "row",
                    alignItems: "center",
                    gap: 8,
                    backgroundColor: "transparent",
                    linearGradient: null,
                    borderColor: "transparent",
                    borderWidth: 0,
                    borderRadius: 0,
                    opacity: 1,
                    rotate: 0,
                    boxShadow: null,
                    zIndex: 0,
                  },
                  children: [
                    {
                      type: "view",
                      name: "brandIcon",
                      style: {
                        width: 36,
                        height: 36,
                        justifyContent: "center",
                        alignItems: "center",
                        backgroundColor: "rgba(255,255,255,0.10)",
                        linearGradient: null,
                        borderColor: "rgba(255,255,255,0.15)",
                        borderWidth: 1,
                        borderRadius: 16,
                        opacity: 1,
                        rotate: 0,
                        boxShadow: null,
                        zIndex: 0,
                      },
                      children: [
                        {
                          type: "text",
                          name: "brandIconText",
                          style: {
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 18,
                            fontWeight: 800,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "rgba(255,255,255,0.90)",
                            lineHeight: 1,
                            textAlign: "center",
                            whiteSpace: "normal",
                            textShadow: null,
                          },
                          content: "✦",
                        },
                      ],
                    },
                    {
                      type: "view",
                      name: "brandText",
                      style: {
                        flexDirection: "column",
                        backgroundColor: "transparent",
                        linearGradient: null,
                        borderColor: "transparent",
                        borderWidth: 0,
                        borderRadius: 0,
                        opacity: 1,
                        rotate: 0,
                        boxShadow: null,
                        zIndex: 0,
                      },
                      children: [
                        {
                          type: "text",
                          name: "tagline",
                          style: {
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 14,
                            fontWeight: 700,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "rgba(255,255,255,0.92)",
                            lineHeight: 1.1,
                            textAlign: "left",
                            whiteSpace: "normal",
                            textShadow: null,
                          },
                          content: "Yoga Canvas",
                        },
                        {
                          type: "text",
                          name: "subtitle",
                          style: {
                            marginTop: 2,
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 11,
                            fontWeight: 600,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "rgba(255,255,255,0.55)",
                            lineHeight: 1.3,
                            textAlign: "left",
                            whiteSpace: "normal",
                            textShadow: null,
                          },
                          content: "基于 Yoga Layout 的 Canvas 画布引擎",
                        },
                      ],
                    },
                  ],
                },
                {
                  type: "view",
                  name: "toggleLocale",
                  style: {
                    paddingTop: 10,
                    paddingRight: 12,
                    paddingBottom: 10,
                    paddingLeft: 12,
                    backgroundColor: "rgba(255,255,255,0.07)",
                    linearGradient: null,
                    borderColor: "rgba(255,255,255,0.12)",
                    borderWidth: 1,
                    borderRadius: 24,
                    opacity: 1,
                    rotate: 0,
                    boxShadow: null,
                    zIndex: 0,
                  },
                  children: [
                    {
                      type: "text",
                      name: "toggleLocaleText",
                      style: {
                        backgroundColor: "transparent",
                        linearGradient: null,
                        borderColor: "transparent",
                        borderWidth: 0,
                        borderRadius: 0,
                        opacity: 1,
                        rotate: 0,
                        boxShadow: null,
                        zIndex: 0,
                        fontSize: 11,
                        fontWeight: 700,
                        fontStyle: "normal",
                        fontFamily: "sans-serif",
                        color: "rgba(255,255,255,0.75)",
                        lineHeight: 1.3,
                        textAlign: "center",
                        whiteSpace: "nowrap",
                        textShadow: null,
                      },
                      content: "中文",
                    },
                  ],
                },
              ],
            },
            {
              type: "view",
              name: "hero",
              style: {
                marginTop: 56,
                backgroundColor: "transparent",
                linearGradient: null,
                borderColor: "transparent",
                borderWidth: 0,
                borderRadius: 0,
                opacity: 1,
                rotate: 0,
                boxShadow: null,
                zIndex: 0,
              },
              children: [
                {
                  type: "view",
                  name: "heroTitle",
                  style: {
                    marginTop: 24,
                    backgroundColor: "transparent",
                    linearGradient: null,
                    borderColor: "transparent",
                    borderWidth: 0,
                    borderRadius: 0,
                    opacity: 1,
                    rotate: 0,
                    boxShadow: null,
                    zIndex: 0,
                  },
                  children: [
                    {
                      type: "text",
                      name: "heroLead",
                      style: {
                        backgroundColor: "transparent",
                        linearGradient: null,
                        borderColor: "transparent",
                        borderWidth: 0,
                        borderRadius: 0,
                        opacity: 1,
                        rotate: 0,
                        boxShadow: null,
                        zIndex: 0,
                        fontSize: 46,
                        fontWeight: 800,
                        fontStyle: "normal",
                        fontFamily: "sans-serif",
                        color: "rgba(255,255,255,0.95)",
                        lineHeight: 1.0,
                        textAlign: "left",
                        whiteSpace: "normal",
                        textShadow: null,
                      },
                      content: "一个面向",
                    },
                    {
                      type: "text",
                      name: "heroHighlight",
                      style: {
                        marginTop: 6,
                        backgroundColor: "transparent",
                        linearGradient: {
                          type: "linear",
                          start: {
                            x: 0,
                            y: 0.5,
                          },
                          end: {
                            x: 1,
                            y: 0.5,
                          },
                          colors: [
                            {
                              offset: 0,
                              color: "#f4a8ff",
                            },
                            {
                              offset: 1,
                              color: "#ddd6ff",
                            },
                          ],
                        },
                        borderColor: "transparent",
                        borderWidth: 0,
                        borderRadius: 0,
                        opacity: 1,
                        rotate: 0,
                        boxShadow: null,
                        zIndex: 0,
                        fontSize: 46,
                        fontWeight: 800,
                        fontStyle: "normal",
                        fontFamily: "sans-serif",
                        color: "transparent",
                        lineHeight: 1.2,
                        textAlign: "left",
                        whiteSpace: "normal",
                        textShadow: {
                          color: "transparent",
                          blur: 0,
                          offsetX: 0,
                          offsetY: 0,
                        },
                      },
                      content: "布局与可视化编辑",
                    },
                    {
                      type: "text",
                      name: "heroTail",
                      style: {
                        marginTop: 6,
                        backgroundColor: "transparent",
                        linearGradient: null,
                        borderColor: "transparent",
                        borderWidth: 0,
                        borderRadius: 0,
                        opacity: 1,
                        rotate: 0,
                        boxShadow: null,
                        zIndex: 0,
                        fontSize: 46,
                        fontWeight: 800,
                        fontStyle: "normal",
                        fontFamily: "sans-serif",
                        color: "rgba(255,255,255,0.95)",
                        lineHeight: 1.0,
                        textAlign: "left",
                        whiteSpace: "normal",
                        textShadow: null,
                      },
                      content: "的 Canvas 引擎与组件库",
                    },
                  ],
                },
                {
                  type: "text",
                  name: "intro",
                  style: {
                    width: 560,
                    marginTop: 16,
                    backgroundColor: "transparent",
                    linearGradient: null,
                    borderColor: "transparent",
                    borderWidth: 0,
                    borderRadius: 0,
                    opacity: 1,
                    rotate: 0,
                    boxShadow: null,
                    zIndex: 0,
                    fontSize: 14,
                    fontWeight: 500,
                    fontStyle: "normal",
                    fontFamily: "sans-serif",
                    color: "rgba(255,255,255,0.65)",
                    lineHeight: 1.7,
                    textAlign: "left",
                    whiteSpace: "normal",
                    textShadow: null,
                  },
                  content:
                    "用 Yoga（Flexbox）计算布局，把 View/Text/Image/ScrollView 这类节点树渲染到 Canvas；并提供命中测试、选中高亮、缩放平移与属性调参等编辑能力，支持导出 JSON / DOM / 图片，适配 H5 与微信小程序。",
                },
                {
                  type: "view",
                  name: "actions",
                  style: {
                    marginTop: 32,
                    backgroundColor: "transparent",
                    linearGradient: null,
                    borderColor: "transparent",
                    borderWidth: 0,
                    borderRadius: 0,
                    opacity: 1,
                    rotate: 0,
                    boxShadow: null,
                    zIndex: 0,
                  },
                  children: [
                    {
                      type: "view",
                      name: "cta",
                      style: {
                        flexDirection: "row",
                        alignItems: "center",
                        gap: 8,
                        paddingTop: 12,
                        paddingRight: 16,
                        paddingBottom: 12,
                        paddingLeft: 16,
                        width: 110,
                        height: 40,
                        backgroundColor: "#ffffff",
                        linearGradient: null,
                        borderColor: "transparent",
                        borderWidth: 0,
                        borderRadius: 16,
                        opacity: 1,
                        rotate: 0,
                        boxShadow: {
                          offsetX: 0,
                          offsetY: 18,
                          blur: 60,
                          color: "rgba(0,0,0,0.35)",
                        },
                        zIndex: 0,
                      },
                      children: [
                        {
                          type: "text",
                          name: "ctaLabel",
                          style: {
                            width: "auto",
                            flexShrink: 1,
                            flexBasis: "auto",
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 14,
                            fontWeight: 800,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "#0f172a",
                            lineHeight: 1.1,
                            textAlign: "left",
                            whiteSpace: "nowrap",
                            textShadow: null,
                          },
                          content: "立即体验",
                        },
                        {
                          type: "text",
                          name: "ctaArrow",
                          style: {
                            flexShrink: 1,
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 16,
                            fontWeight: 900,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "#0f172a",
                            lineHeight: 1,
                            textAlign: "left",
                            whiteSpace: "nowrap",
                            textShadow: null,
                          },
                          content: "→",
                        },
                      ],
                    },
                  ],
                },
                {
                  type: "view",
                  name: "stats",
                  style: {
                    width: 560,
                    flexDirection: "row",
                    flexWrap: "wrap",
                    gap: 12,
                    marginTop: 40,
                    backgroundColor: "transparent",
                    linearGradient: null,
                    borderColor: "transparent",
                    borderWidth: 0,
                    borderRadius: 0,
                    opacity: 1,
                    rotate: 0,
                    boxShadow: null,
                    zIndex: 0,
                  },
                  children: [
                    {
                      type: "view",
                      name: "stat_layout",
                      style: {
                        width: 274,
                        paddingTop: 12,
                        paddingRight: 16,
                        paddingBottom: 12,
                        paddingLeft: 16,
                        backgroundColor: "rgba(255,255,255,0.07)",
                        linearGradient: null,
                        borderColor: "rgba(255,255,255,0.12)",
                        borderWidth: 1,
                        borderRadius: 16,
                        opacity: 1,
                        rotate: 0,
                        boxShadow: {
                          offsetX: 0,
                          offsetY: 18,
                          blur: 60,
                          color: "rgba(0,0,0,0.18)",
                        },
                        zIndex: 0,
                      },
                      children: [
                        {
                          type: "text",
                          name: "stat_layout_label",
                          style: {
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 11,
                            fontWeight: 700,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "rgba(255,255,255,0.55)",
                            lineHeight: 1.3,
                            textAlign: "left",
                            whiteSpace: "normal",
                            textShadow: null,
                          },
                          content: "Yoga 布局",
                        },
                        {
                          type: "text",
                          name: "stat_layout_value",
                          style: {
                            marginTop: 4,
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 14,
                            fontWeight: 800,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "rgba(255,255,255,0.90)",
                            lineHeight: 1.3,
                            textAlign: "left",
                            whiteSpace: "normal",
                            textShadow: null,
                          },
                          content: "Yoga Flexbox",
                        },
                      ],
                    },
                    {
                      type: "view",
                      name: "stat_render",
                      style: {
                        width: 274,
                        paddingTop: 12,
                        paddingRight: 16,
                        paddingBottom: 12,
                        paddingLeft: 16,
                        backgroundColor: "rgba(255,255,255,0.07)",
                        linearGradient: null,
                        borderColor: "rgba(255,255,255,0.12)",
                        borderWidth: 1,
                        borderRadius: 16,
                        opacity: 1,
                        rotate: 0,
                        boxShadow: {
                          offsetX: 0,
                          offsetY: 18,
                          blur: 60,
                          color: "rgba(0,0,0,0.18)",
                        },
                        zIndex: 0,
                      },
                      children: [
                        {
                          type: "text",
                          name: "stat_render_label",
                          style: {
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 11,
                            fontWeight: 700,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "rgba(255,255,255,0.55)",
                            lineHeight: 1.3,
                            textAlign: "left",
                            whiteSpace: "normal",
                            textShadow: null,
                          },
                          content: "渲染输出",
                        },
                        {
                          type: "text",
                          name: "stat_render_value",
                          style: {
                            marginTop: 4,
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 14,
                            fontWeight: 800,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "rgba(255,255,255,0.90)",
                            lineHeight: 1.3,
                            textAlign: "left",
                            whiteSpace: "normal",
                            textShadow: null,
                          },
                          content: "Canvas (H5/WX) / DOM",
                        },
                      ],
                    },
                    {
                      type: "view",
                      name: "stat_editor",
                      style: {
                        width: 274,
                        paddingTop: 12,
                        paddingRight: 16,
                        paddingBottom: 12,
                        paddingLeft: 16,
                        backgroundColor: "rgba(255,255,255,0.07)",
                        linearGradient: null,
                        borderColor: "rgba(255,255,255,0.12)",
                        borderWidth: 1,
                        borderRadius: 16,
                        opacity: 1,
                        rotate: 0,
                        boxShadow: {
                          offsetX: 0,
                          offsetY: 18,
                          blur: 60,
                          color: "rgba(0,0,0,0.18)",
                        },
                        zIndex: 0,
                      },
                      children: [
                        {
                          type: "text",
                          name: "stat_editor_label",
                          style: {
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 11,
                            fontWeight: 700,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "rgba(255,255,255,0.55)",
                            lineHeight: 1.3,
                            textAlign: "left",
                            whiteSpace: "normal",
                            textShadow: null,
                          },
                          content: "编辑交互",
                        },
                        {
                          type: "text",
                          name: "stat_editor_value",
                          style: {
                            marginTop: 4,
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 14,
                            fontWeight: 800,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "rgba(255,255,255,0.90)",
                            lineHeight: 1.3,
                            textAlign: "left",
                            whiteSpace: "normal",
                            textShadow: null,
                          },
                          content: "HitTest / Select / Inspect",
                        },
                      ],
                    },
                    {
                      type: "view",
                      name: "stat_export",
                      style: {
                        width: 274,
                        paddingTop: 12,
                        paddingRight: 16,
                        paddingBottom: 12,
                        paddingLeft: 16,
                        backgroundColor: "rgba(255,255,255,0.07)",
                        linearGradient: null,
                        borderColor: "rgba(255,255,255,0.12)",
                        borderWidth: 1,
                        borderRadius: 16,
                        opacity: 1,
                        rotate: 0,
                        boxShadow: {
                          offsetX: 0,
                          offsetY: 18,
                          blur: 60,
                          color: "rgba(0,0,0,0.18)",
                        },
                        zIndex: 0,
                      },
                      children: [
                        {
                          type: "text",
                          name: "stat_export_label",
                          style: {
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 11,
                            fontWeight: 700,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "rgba(255,255,255,0.55)",
                            lineHeight: 1.3,
                            textAlign: "left",
                            whiteSpace: "normal",
                            textShadow: null,
                          },
                          content: "导出格式",
                        },
                        {
                          type: "text",
                          name: "stat_export_value",
                          style: {
                            marginTop: 4,
                            backgroundColor: "transparent",
                            linearGradient: null,
                            borderColor: "transparent",
                            borderWidth: 0,
                            borderRadius: 0,
                            opacity: 1,
                            rotate: 0,
                            boxShadow: null,
                            zIndex: 0,
                            fontSize: 14,
                            fontWeight: 800,
                            fontStyle: "normal",
                            fontFamily: "sans-serif",
                            color: "rgba(255,255,255,0.90)",
                            lineHeight: 1.3,
                            textAlign: "left",
                            whiteSpace: "normal",
                            textShadow: null,
                          },
                          content: "JSON / DOM / Image",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  },
];

export function getSeedTemplate(id: string): SeedTemplate | null {
  return seedTemplates.find((t) => t.id === id) ?? null;
}
